---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: sample-container
        image: sachinvarghese333/app:51
        ports:
        - containerPort: 8080
                                
