---
apiVersion: v1
kind: Service
metadata:
  name: my-service-balancer
  labels:
    service: my-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8080 #port which container is running
    nodePort: 31222
    protocol: TCP
