apiVersion: v1
kind: Service
metadata:
  name: lb-devops-case-study
  labels:
    service: lb-devops-case-study
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 31000
    targetPort: 8080
    protocol: TCP
  selector:
      app: app-devops-case-study
